version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./src/src.csproj --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish ./src/src.csproj
after_build:
  # For once the build has completed
artifacts:
 - path: .\artifacts\**\*.nupkg
   name: NuGet
clone_depth: 1
test_script:
  # restore packages for our unit tests
on_finish :
  # any cleanup in here
deploy: off